### ISSUE TITLE
Stream Scheduler

### ISSUE THREAD

**Issue by ekkolyth** [michaelmcnees/extralife-dash#2]
As a user, I should be able to edit the schedule for the stream by adding, moving, and removing segments. 

### Segments
- User should be able to add a segment into the schedule.
- Segments should have a Title that can be input by the user
- Once the segment has been added, it should be able to be assigned to a timeslot
- Existing Segments should be able to be deleted.
- Segments will either need to be able to be assigned a length, _or_ a blank space on the schedule would need to be read as still having the most recent timeslot active. 

### Timeslots
- A timeslot should be exactly 1 hour of real time
- When a timeslot is active, the associated Segment title should appear in the "Now" section of the UI
- The Segment following the currently active segment should appear in the "Up Next" section of the UI

**Comment by michaelmcnees** [comment]
This is done
